Repository officebeatz/OfficeBeatz2, pull requests merged in 2020-12, with the labels that each got.

#110 Removed COVID-19 Message
  views/components/banner-message.pug
Labels: task

#112 Fix timing feature
  public/javascripts/PageTimeTracker.js
  routes/dbx.js
  routes/utils.js
Labels: bug

#115 Timing should work for multiple device logins
  public/javascripts/PageTimeTracker.js
  routes/index.js
  routes/utils.js
Labels: bug

#116 More accurate timing implemented
  app.js
  package.json
  public/javascripts/PageTimeTracker.js
  public/javascripts/socket.io.js
  routes/index.js
  routes/utils.js
  views/layouts/layout.pug
Labels: bug

#118 Made timing more accurate by a lot
  app.js
  routes/index.js
  routes/utils.js
Labels: enhancement

#119 Minor fix
  routes/utils.js
Labels: bug, enhancement

#120 Small optimization on logging in
  routes/index.js
Labels: enhancement

#121 Made timing more accurate
  app.js
  routes/index.js
  routes/utils.js
Labels: enhancement

#122 Improvingaestheticseaseofuse
  .env.example
  package.json
  public/stylesheets/style.sass
  views/components/form-holder/interval-form.pug
  views/components/getting-started-tab.pug
Labels: enhancement
